export class UserDetails{
    userId:number;
    firstName:string;
    lastName:string;
    userName:string;
    alterName:string;
    password:string;
    email:string;
    phoneNo:string;
    birthDate:Date;
    gender:string;
    profilePicture:string;
    coverImage:string;
    address:string;
    quotes:string;
    about:string;
    work:string;
    schoolName:string;
    collegeName:string;
}